# Generated by Django 5.1.4 on 2024-12-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventlog_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': 'event_log'},
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table='event_log',
        ),
    ]
