# Generated by Django 5.1.4 on 2024-12-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_eventlog_options_alter_eventlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='original_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventlog'),
        ),
    ]
