# Generated by Django 5.1.4 on 2024-12-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_archivedevent_original_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='event',
            new_name='events',
        ),
    ]
